# @package _global_

defaults:
  - default
  - override /model: ecg_classifier
  - override /modality: ${data}/arrhythmia
  - override /data: ecg
  - override /logger: tensorboard

data:
  downstream: true

trainer:
  fast_dev_run: true