# @package _global_

defaults:
  - /callbacks/early_stopping
  - override /callbacks: default
  - override /hydra/sweeper: optuna
  
# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: ???

task_name: "hparams_search"
tags: ["hparams_search"]

# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN"

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    storage: null
    study_name: null


    n_jobs: 1
    direction: ???
    n_trials: ???

    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 10 # number of random sampling runs before optimization starts

    params: ???

callbacks:
  early_stopping:
    verbose: True
    patience: 15