# @package _global_

defaults:
  - default
  - override /model: ecg_classifier

optimized_metric: "val_f1"

hydra:
  sweeper:
    n_jobs: 1
    direction: maximize
    n_trials: 120

    params:
      model.learning_rate: interval(0.000001, 0.3)
      model.weight_decay: interval(0.0000001, 0.1)
      data.batch_size: choice(16, 32, 64, 128)
      model.layer_decay: interval(0.2, 0.8)
      
      model.warmup_epochs: 15 # 5%
      trainer.max_epochs: 300

callbacks:
  early_stopping:
    monitor: "val_f1"
    mode: max