
neptune:
  _target_: lightning.pytorch.loggers.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project: bat/ipole
  log_model_checkpoints: True
  prefix: ""
  dependencies: infer
  tags: null # Currently not supported as conversion between omegaconf.listconfig.ListConfig and list is not easy
  description: null