# @package _global_

defaults:
  - default
  - override /model: mae
  - override /modality: ${data}/arrhythmia
  - override /data: ecg
  - override /logger: tensorboard

data:
  batch_size: 128

model:
  mask_ratio: 0.75
  learning_rate: 1e-4
  pretrained_weights: null

trainer:
  max_epochs: 200
  # Use only a small subset of data
  overfit_batches: 5
  gradient_clip_val: 0.0
  accumulate_grad_batches: 1