repo_name: "ipole/projection"
image_tag: "latest"
role_arn: "arn:aws:iam::864981760979:role/Hydra-Sagemaker"
instance_type: "ml.g5.4xlarge"
instance_count: 1
volume_size_in_gb: 10
max_runtime_in_seconds: 600

entrypoint: sm_entrypoint.py