name: Build Docs and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rye environment
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          source "${{ github.workspace }}/.rye/env"
          rye sync --no-lock

      - name: Build docs
        run: |
          source "${{ github.workspace }}/.rye/env"
          rye run build_docs

      - name: Upload 'site' artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site

  pages:
    name: Prepare Public Folder & Upload for Pages
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      - name: Download 'site' artifact
        uses: actions/download-artifact@v3
        with:
          name: site

      - name: Determine PAGES_PREFIX
        id: prefix
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PAGES_PREFIX=mr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            if [ "${{ github.ref_name }}" = "main" ]; then
              echo "PAGES_PREFIX=" >> $GITHUB_ENV
            fi
          fi

      - name: Create public folder (equivalent to GitLab "pages" job script)
        run: |
          mkdir -p public
          cp -r notebooks/quarto_book/_book/* public/ || true
          
          mkdir -p public/docs
          cp -r site/* public/docs/ || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: pages
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy with GitHub Pages Action
        uses: actions/deploy-pages@v1
